services:
  frontend:
    build: .
    platform: linux/amd64
    ports:
      - 80:8000
    environment:
      GATSBY_GA_TRACKING_ID: ${GATSBY_GA_TRACKING_ID}
      GATSBY_MAPBOX_API_TOKEN: ${GATSBY_MAPBOX_API_TOKEN}
      GATSBY_MAPBOX_USER: ${GATSBY_MAPBOX_USER}
    container_name: cre_build
    develop:
      watch:
        - action: sync
          path: .
          target: /src
    stdin_open: true
    volumes:
      - ./:/app
      - /app/node_modules
    restart: always
