services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    platform: linux/amd64
    ports:
      - "8000:8000"
    environment:
      - NODE_ENV=${NODE_ENV:-development}
      - GATSBY_TELEMETRY_DISABLED=1
      - HOST=0.0.0.0
      - GATSBY_GA_TRACKING_ID=${GATSBY_GA_TRACKING_ID}
      - GATSBY_MAPBOX_API_TOKEN=${GATSBY_MAPBOX_API_TOKEN}
      - GATSBY_MAPBOX_USER=${GATSBY_MAPBOX_USER}
      - SHARP_IGNORE_GLOBAL_LIBVIPS=1
    container_name: cre_build
    stdin_open: true
    tty: true
    volumes:
      - .:/app
      - /app/node_modules
    command: ["npm", "run", "develop"]

volumes: {}

# Start with:
# docker compose up --build
